# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K9YGa50dyfor4DAC5hsHW09aRmJ1YFZu
"""

import streamlit as st

st.title("mi primera aplicación en streamlit")
st.header("este es mi encabezado")
st.subheader("este es un subencabezado")
st.write("esta es una introducción a streamlit")